language: java
sudo: false # faster builds

before_install:
  - chmod +x ./gradlew
  - pip install --user codecov

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - codecov